name: Bridgetown CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'

    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Ruby dependencies
      run: bundle install --with test

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node.js dependencies with Yarn
      run: yarn install

    - name: Build Frontend Assets
      run: bin/bridgetown frontend:build

    - name: Run tests
      run: bin/bridgetown test

    - name: Run standardrb
      run: standardrb

    - name: Build site
      run: bin/bridgetown deploy

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'

    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Ruby dependencies
      run: bundle install --with test

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node.js dependencies with Yarn
      run: yarn install

    - name: Build Frontend Assets
      run: bin/bridgetown frontend:build

    - name: Build site
      run: bin/bridgetown deploy

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Create Deployment
      id: create_deployment
      uses: actions/github-script@v6
      with:
        script: |
          const { data: deployment } = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.ref,
            required_contexts: [],  // Bypass status checks
            environment: 'production',
            transient_environment: false,
            auto_merge: false
          });
          core.setOutput('deployment_id', deployment.id);

    - name: Deploy to Netlify
      run: netlify deploy --prod --message "${{ github.event.head_commit.message }}"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Set Deployment Status to Success
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: ${{ steps.create_deployment.outputs.deployment_id }},
            state: 'success',
            environment: 'production',
            environment_url: 'https://rosecityrobotics.com',  // Replace with your Netlify site URL
            log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          });

    - name: Set Deployment Status to Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: ${{ steps.create_deployment.outputs.deployment_id }},
            state: 'failure',
            environment: 'production',
            log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          });
