name: Bridgetown CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        bundle install

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Specify your Node.js version, adjust as needed
        cache: 'yarn'  # Enables caching of Yarn modules

    - name: Install Node.js dependencies with Yarn
      run: |
        yarn install

    - name: Build Frontend Assets
      run: |
        bin/bridgetown frontend:build

    - name: Run tests
      run: |
        bin/bridgetown test

    - name: Run standardrb
      run: |
        standardrb

    - name: Build site
      run: |
        bin/bridgetown build

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      if: success()  # This ensures deployment happens only if previous steps are successful
      run: netlify deploy --prod --message "${{ github.event.head_commit.message }}"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
