name: Bridgetown CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        bundle install

    - name: Run tests
      run: |
        bin/bridgetown test

    - name: Run standardrb
      run: |
        standardrb

    - name: Build site
      run: |
        bin/bridgetown build

    - name: Deploy to Netlify
      if: success()
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/663eb45a98c32262d755cc11
